/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        'heading': ['var(--font-heading)', 'Poppins', 'system-ui', 'sans-serif'],
        'display': ['var(--font-display)', 'Space Grotesk', 'system-ui', 'sans-serif'],
        'body': ['var(--font-body)', 'Inter', 'system-ui', 'sans-serif'],
        'mono': ['var(--font-mono)', 'Space Mono', 'monospace'],
      },
      fontSize: {
        'hero': ['clamp(3rem, 6vw, 5rem)', { lineHeight: '1.05', letterSpacing: '-0.02em' }],
        'display': ['clamp(2.5rem, 5vw, 4rem)', { lineHeight: '1.1', letterSpacing: '-0.015em' }],
        'h1': ['clamp(2rem, 4vw, 3rem)', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
        'h2': ['clamp(1.5rem, 3vw, 2rem)', { lineHeight: '1.3', letterSpacing: '-0.005em' }],
        'h3': ['clamp(1.25rem, 2.5vw, 1.5rem)', { lineHeight: '1.3' }],
        'h4': ['clamp(1.125rem, 2vw, 1.25rem)', { lineHeight: '1.4' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6' }],
        'body': ['1rem', { lineHeight: '1.6' }],
        'body-sm': ['0.875rem', { lineHeight: '1.5' }],
        'caption': ['0.75rem', { lineHeight: '1.4' }],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Gen-Z Accent Colors
        'accent-pink': {
          DEFAULT: '#FF929F',
          50: '#FFF5F6',
          100: '#FFE8EA',
          500: '#FF929F',
          600: '#FF7A89',
          700: '#FF6273',
        },
        'accent-sky': {
          DEFAULT: '#92CAFF',
          50: '#F0F8FF',
          100: '#E1F1FF',
          500: '#92CAFF',
          600: '#7AB8FF',
          700: '#62A6FF',
        },
        'accent-yellow': {
          DEFAULT: '#FFD392',
          50: '#FFFBF0',
          100: '#FFF7E1',
          500: '#FFD392',
          600: '#FFC87A',
          700: '#FFBD62',
        },
        'accent-aqua': {
          DEFAULT: '#92F2FF',
          50: '#F0FEFF',
          100: '#E1FDFF',
          500: '#92F2FF',
          600: '#7AEBFF',
          700: '#62E4FF',
        },
        'accent-mint': {
          DEFAULT: '#92FFB0',
          50: '#F0FFF5',
          100: '#E1FFEB',
          500: '#92FFB0',
          600: '#7AFF9E',
          700: '#62FF8C',
        },
        'accent-purple': {
          DEFAULT: '#A192FF',
          50: '#F5F0FF',
          100: '#EBE1FF',
          500: '#A192FF',
          600: '#8F7AFF',
          700: '#7D62FF',
        },
        'accent-violet': {
          DEFAULT: '#DC92FF',
          50: '#FDF0FF',
          100: '#FBE1FF',
          500: '#DC92FF',
          600: '#D37AFF',
          700: '#CA62FF',
        },
        'accent-grey': {
          DEFAULT: '#BCC0C5',
          50: '#F8F9FA',
          100: '#F1F3F5',
          500: '#BCC0C5',
          600: '#A8ADB3',
          700: '#949AA1',
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 0.25rem)",
        sm: "calc(var(--radius) - 0.5rem)",
        'xl': '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '112': '28rem',
        '128': '32rem',
      },
      boxShadow: {
        'glow-pink': '0 0 20px rgba(255, 146, 159, 0.3)',
        'glow-sky': '0 0 20px rgba(146, 202, 255, 0.3)',
        'glow-yellow': '0 0 20px rgba(255, 211, 146, 0.3)',
        'glow-aqua': '0 0 20px rgba(146, 242, 255, 0.3)',
        'glow-mint': '0 0 20px rgba(146, 255, 176, 0.3)',
        'glow-purple': '0 0 20px rgba(161, 146, 255, 0.3)',
        'glow-violet': '0 0 20px rgba(220, 146, 255, 0.3)',
        'premium': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        'inner-lg': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.1)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        'glow-pulse': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        'shimmer': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'subtle-shine': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'float': 'float 3s ease-in-out infinite',
        'fade-in': 'fade-in 0.5s ease-out',
        'slide-up': 'slide-up 0.6s ease-out',
        'scale-in': 'scale-in 0.4s ease-out',
        'subtle-shine': 'subtle-shine 2s ease-in-out infinite',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
