import mongoose, { Schema, Document, Model } from 'mongoose';

/**
 * @interface IUserProfile
 * Defines the structure of a user's professional profile document in MongoDB.
 * This data is the primary input for the AI recommendation engine.
 */
export interface IUserProfile extends Document {
  userId: mongoose.Schema.Types.ObjectId; // Link to the main User model
  status: 'Student' | 'Professional';
  institution: string;
  careerGoal: string;
  currentProject: string;
  skills: string[];
  projectEmbedding?: number[]; // Stores the AI-generated vector for semantic search
}

const UserProfileSchema: Schema<IUserProfile> = new Schema(
  {
    /**
     * A unique reference to the main user document. This creates a one-to-one relationship.
     */
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User', // This must match the name of your main User model
      required: true,
      unique: true,
      index: true, // Index for faster lookups by user ID
    },

    status: {
      type: String,
      enum: ['Student', 'Professional'],
      required: [true, 'User status is required (Student or Professional).'],
    },

    /**
     * The user's current or former institution/company. Indexed for keyword filtering.
     */
    institution: {
      type: String,
      trim: true,
      index: true,
    },

    /**
     * The user's stated career goal. Indexed for keyword filtering.
     */
    careerGoal: {
      type: String,
      required: [true, 'Career goal is required.'],
      trim: true,
      index: true,
    },

    /**
     * A detailed description of the user's current project. This is the primary text
     * used to generate AI embeddings for semantic matching.
     */
    currentProject: {
      type: String,
      required: [true, 'A current project description is required.'],
      trim: true,
      minlength: [20, 'Project description must be at least 20 characters long.'],
    },

    /**
     * A list of the user's skills. Can be used for secondary filtering.
     */
    skills: {
      type: [{ type: String, trim: true }],
      default: [],
    },

    /**
     * Stores the numerical vector representation of the 'currentProject' field.
     * This is generated by an AI model (e.g., OpenAI's text-embedding-ada-002).
     * It is the core data used for calculating semantic similarity between users.
     * Note: For very large-scale applications (1M+ users), storing embeddings in a
     * dedicated vector database like Pinecone or Weaviate is more performant.
     */
    projectEmbedding: {
      type: [Number],
      default: [],
    },
  },
  {
    /**
     * Automatically adds `createdAt` and `updatedAt` timestamps to each document.
     */
    timestamps: true,
  }
);

const UserProfile: Model<IUserProfile> = mongoose.model<IUserProfile>('UserProfile', UserProfileSchema);

export default UserProfile;


